### ISSUE TITLE
API usage example

### ISSUE THREAD

**Issue by DerouineauNicolas** [melowntech/libvef#1]
Hello,
Is there any reference on how to use the library API ?

**Comment by vaclavblazek** [comment]
Hi,

libvef is a simplistic library for writing/reading our own VEF archives, see documentation referenced from main readme. It is nothing more than JSON metadata and bunch of textured meshes.

The API is used in our tools, so I can point to the source code. However, it may be a bit hard for you to use the library because it is made to be plugged in our buildsystem together with other our libraries, to be statically linked to the binary.

The [vts-tools](https://github.com/melowntech/vts-tools) project uses this library so you may have a look how to compile the library and how to use it; nota bene: project uses git submodules, so you need to use `git clone --recursive`.

libvef is used in these tools: [vef2slpk](https://github.com/melowntech/vts-tools/blob/master/tools/src/tools/vef2slpk.cpp) and [vef2vts](https://github.com/melowntech/vts-tools/blob/master/tools/src/tools/vef2vts.cpp). However, only archive reading. Unfortunately, archive creation is in no OSS tool.

**Comment by DerouineauNicolas** [comment]
Thanks for your prompt answer ! I was interested by the archive creation tool, but I understand the absence of OSS implementation. I'm going to have a look to vfs-tools.
